import { User } from './types';

export const MAX_FIRST_DEGREE_FRIENDS = 8;

export const MOCK_USERS_DATA: User[] = [
  { id: 'user1', name: 'Alice Smith', bio: 'Loves hiking and coding.', profileImageUrl: 'https://picsum.photos/seed/alice/100/100', phoneNumber: '5550000001', password: 'password123', firstDegreeFriendIds: ['user2', 'user3', 'user4', 'user10'], approvedSecondDegreeConnections: new Set() },
  { id: 'user2', name: 'Bob Johnson', bio: 'Coffee enthusiast, gamer.', profileImageUrl: 'https://picsum.photos/seed/bob/100/100', phoneNumber: '5550000002', password: 'password123', firstDegreeFriendIds: ['user1', 'user5', 'user6', 'user11'], approvedSecondDegreeConnections: new Set() },
  { id: 'user3', name: 'Carol Williams', bio: 'Musician and artist.', profileImageUrl: 'https://picsum.photos/seed/carol/100/100', phoneNumber: '5550000003', password: 'password123', firstDegreeFriendIds: ['user1', 'user7', 'user8', 'user12'], approvedSecondDegreeConnections: new Set() },
  { id: 'user4', name: 'David Brown', bio: 'Travels the world.', profileImageUrl: 'https://picsum.photos/seed/dave/100/100', phoneNumber: '5550000004', password: 'password123', firstDegreeFriendIds: ['user1', 'user9', 'user13'], approvedSecondDegreeConnections: new Set() },
  { id: 'user5', name: 'Eve Davis', bio: 'Chef and food blogger.', profileImageUrl: 'https://picsum.photos/seed/eve/100/100', phoneNumber: '5550000005', password: 'password123', firstDegreeFriendIds: ['user2', 'user14'], approvedSecondDegreeConnections: new Set() },
  { id: 'user6', name: 'Frank Miller', bio: 'Photographer.', profileImageUrl: 'https://picsum.photos/seed/frank/100/100', phoneNumber: '5550000006', password: 'password123', firstDegreeFriendIds: ['user2', 'user15'], approvedSecondDegreeConnections: new Set() },
  { id: 'user7', name: 'Grace Wilson', bio: 'Yoga instructor.', profileImageUrl: 'https://picsum.photos/seed/grace/100/100', phoneNumber: '5550000007', password: 'password123', firstDegreeFriendIds: ['user3', 'user16'], approvedSecondDegreeConnections: new Set() },
  { id: 'user8', name: 'Henry Moore', bio: 'Reads a lot.', profileImageUrl: 'https://picsum.photos/seed/henry/100/100', phoneNumber: '5550000008', password: 'password123', firstDegreeFriendIds: ['user3', 'user17'], approvedSecondDegreeConnections: new Set() },
  { id: 'user9', name: 'Ivy Taylor', bio: 'Tech startup founder.', profileImageUrl: 'https://picsum.photos/seed/ivy/100/100', phoneNumber: '5550000009', password: 'password123', firstDegreeFriendIds: ['user4', 'user18'], approvedSecondDegreeConnections: new Set() },
  { id: 'user10', name: 'Jack Anderson', bio: 'Loves sports.', profileImageUrl: 'https://picsum.photos/seed/jack/100/100', phoneNumber: '5550000010', password: 'password123', firstDegreeFriendIds: ['user1', 'user19'], approvedSecondDegreeConnections: new Set() },
  { id: 'user11', name: 'Kate Thomas', bio: 'Enjoys gardening.', profileImageUrl: 'https://picsum.photos/seed/kate/100/100', phoneNumber: '5550000011', password: 'password123', firstDegreeFriendIds: ['user2', 'user20'], approvedSecondDegreeConnections: new Set() },
  { id: 'user12', name: 'Liam Jackson', bio: 'Film buff.', profileImageUrl: 'https://picsum.photos/seed/liam/100/100', phoneNumber: '5550000012', password: 'password123', firstDegreeFriendIds: ['user3', 'user1'], approvedSecondDegreeConnections: new Set() },
  { id: 'user13', name: 'Mia White', bio: 'Dancer.', profileImageUrl: 'https://picsum.photos/seed/mia/100/100', phoneNumber: '5550000013', password: 'password123', firstDegreeFriendIds: ['user4', 'user2'], approvedSecondDegreeConnections: new Set() },
  { id: 'user14', name: 'Noah Harris', bio: 'Software engineer.', profileImageUrl: 'https://picsum.photos/seed/noah/100/100', phoneNumber: '5550000014', password: 'password123', firstDegreeFriendIds: ['user5', 'user3'], approvedSecondDegreeConnections: new Set() },
  { id: 'user15', name: 'Olivia Martin', bio: 'Animal lover.', profileImageUrl: 'https://picsum.photos/seed/olivia/100/100', phoneNumber: '5550000015', password: 'password123', firstDegreeFriendIds: ['user6', 'user4'], approvedSecondDegreeConnections: new Set() },
  { id: 'user16', name: 'Lucas Garcia', bio: 'Skateboarder.', profileImageUrl: 'https://picsum.photos/seed/lucas/100/100', phoneNumber: '5550000016', password: 'password123', firstDegreeFriendIds: ['user7', 'user5'], approvedSecondDegreeConnections: new Set() },
  { id: 'user17', name: 'Chloe Rodriguez', bio: 'Volunteers often.', profileImageUrl: 'https://picsum.photos/seed/chloe/100/100', phoneNumber: '5550000017', password: 'password123', firstDegreeFriendIds: ['user8', 'user6'], approvedSecondDegreeConnections: new Set() },
  { id: 'user18', name: 'Ethan Martinez', bio: 'Plays guitar.', profileImageUrl: 'https://picsum.photos/seed/ethan/100/100', phoneNumber: '5550000018', password: 'password123', firstDegreeFriendIds: ['user9', 'user7'], approvedSecondDegreeConnections: new Set() },
  { id: 'user19', name: 'Ava Hernandez', bio: 'Future astronaut.', profileImageUrl: 'https://picsum.photos/seed/ava/100/100', phoneNumber: '5550000019', password: 'password123', firstDegreeFriendIds: ['user10', 'user8'], approvedSecondDegreeConnections: new Set() },
  { id: 'user20', name: 'Logan Lopez', bio: 'Always learning.', profileImageUrl: 'https://picsum.photos/seed/logan/100/100', phoneNumber: '5550000020', password: 'password123', firstDegreeFriendIds: ['user11', 'user9'], approvedSecondDegreeConnections: new Set() },
];